before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./tex/AntonioMalliaCV.tex
deploy:
  provider: releases
  api_key:
    secure: rSNECX6b3HmS7kDkMgrZK0pBrXsOEKhtTjNFXWNf4nAufpUoaCHQABjOWpDaMxnQNydz9xYs8HqDhU4Zwv6CkOaxPnfUWnnU9mFSjXCPiI+P6eMPVrOQVdQwS1JvoEq0NteN+OoUFFqic48jSmIOQelHf9IWo47Oe24SQLX36O+zfMHnzGw8O46xobJCaAN1Hjk/piqWI4dMi7j47upGWGU5qKg8pwvk89IKz0xUgTZZcsPyUXhC81asYaqezE907l0S6Tn/NTHcMI6xdCfHXaihP9zAtwgCZN81mYHWBTzEaGXnC84qWTBSgXW6/ZsbztiOvnAgvrLjWS88VO5MvSJ+JzmdRFEUvaPR8+fKLKm4ocanxVPqFBgxMV7qdMAOlCtlbtdAJheCurnzt+PcXD79viWiup7jVy7xxrnyjoE4gWNqV7yZCfmyilpBlxFUtjJKdjc0SxcG1RgXTq7BZKQj5lsy9XR9Is/e+RbREKEdgIzfmGnT/7QN2dKLebtTaVTVZ7hkdkNkZXDCxJun2Fs9Z6zvpIAy58GBdtZM9ARcNhmlcw+TIlCpTia0DUI/nu6TdHaDNVaZnVUIZmDQfCVAHnoRc20OznN6Rk2XPXS4N8Glx5SXtWChNDOsEc/TIe7gV/6BStuOXcLEfkJq7q73QbYv+ZpY00dmtZV5dJ8=
  file:
    - ./_build/AntonioMalliaCV.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
